import { configEnvMap, loadWavegridConfig } from '@wavegrid/layout';
import { writeFileSync } from 'fs';
import { join } from 'path';
import c from 'yanse';

import { type Flags, getStore, resolveProjectName } from '../project';

// The config→env projection lives in @wavegrid/layout beside the loader that
// parses it back, so the desktop app applies exactly what the CLI does.
export { applyConfigToEnv, configEnvMap } from '@wavegrid/layout';

/**
 * Build the `.env` lines for a project from its resolved config + secrets.
 * This is the compatibility bridge for anything that still wants env vars
 * (deploy scripts, PM2, the Windows receiver `.cmd`, distributed laptops).
 * The store remains the source of truth; `.env` is a generated artifact.
 */
export function buildEnvLines(flags: Flags, cwd: string): string[] {
  const store = getStore();
  const project = resolveProjectName(store, flags);
  // Selecting a project activates it, so config resolution + secrets agree.
  if (store.getActiveProject() !== project) store.setActiveProject(project);

  const { config } = loadWavegridConfig({ cwd });
  const lines: string[] = [
    '# Generated by `wavegrid env export`. Source of truth is the Wavegrid store',
    `# (${store.paths.root}). CONTAINS SECRETS — do not commit.`,
    ''
  ];

  // Non-secret config, then the required secrets (throws if not generated).
  for (const [k, v] of Object.entries(configEnvMap(config))) lines.push(`${k}=${v}`);
  lines.push(`WG_RECEIVER_KEY=${store.requireSecret(project, 'receiverKey')}`);
  lines.push(`WG_JWT_SECRET=${store.requireSecret(project, 'jwtSecret')}`);

  return lines;
}

/** `wavegrid env export [--file .env]` — write a `.env` for the current project. */
export function runEnvExport(flags: Flags, cwd = process.cwd()): void {
  const lines = buildEnvLines(flags, cwd);
  const target = typeof flags.file === 'string' ? flags.file : '.env';
  const file = join(cwd, target);
  writeFileSync(file, lines.join('\n') + '\n', { mode: 0o600 });

  console.log('');
  console.log(c.green(`  ✓ Wrote ${c.cyan(file)} ${c.gray('(0600, contains secrets — do not commit)')}`));
  console.log('');
}
